image: elixir:1.3

services:
  - postgres:9.6.2

variables:
  MIX_ENV: "test"
  POSTGRES_DB: "workout_demo_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: “s0m3P@ssw0Rd”

stages:
  - test

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.reset

unit-testing:
  stage: test
  tags:
    - elixir
    - phoenix
  script:
    - mix test