image: elixir:1.3

services:
  # - postgres:9.6
  # Using postgis instead of postgres for the postgis extension
  - mdillon/postgis

variables:
  MIX_ENV: "test"

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - apt-get install -y postgresql-client
  # - apt-get install -y postgis*
  - sed -e "s/[#]\?listen_addresses = .*/listen_addresses = '*'/g" -i '/etc/postgresql/9.5/main/postgresql.conf'
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.compile
  - mix ecto.create
  - mix ecto.migrate

unit-testing:
  tags:
    - elixir
    - phoenix
  script:
    - mix test