image: elixir:1.3

services:
  - postgres:9.6

variables:
  POSTGRES_DB: workout_demo_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: “s0m3P@ssw0Rd”

variables:
  MIX_ENV: "test"

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.reset

test:
  script:
    - mix test