image: elixir:1.3

services:
  # - postgres:9.6
  # Instead of postgres -- this is going to pull pg + postgis
  - mdillon/postgis

variables:
  MIX_ENV: "test"

  # These are used by the base image to setup the first database
  POSTGRES_DB: workout_demo_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: "postgres"

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.reset

stages:
  - testing
  - coverage

unit-testing:
  stage: testing
  tags:
    - elixir
    - phoenix
  script:
    - mix test

code-coverage:
  stage: coverage
  tags:
    - elixir
    - phoenix
  script:
    - mix coveralls