image: elixir:1.3

services:
  - postgres:9.4
  # Using postgis instead of postgres for the postgis extension
  # - evili/postgis

variables:
  MIX_ENV: "test"

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - apt-get install -y postgresql-client
  # - apt-get update
  # - apt-get install -y postgis
  - psql --username=postgres
  - \q
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.create
  - mix ecto.migrate

unit-testing:
  tags:
    - elixir
    - phoenix
  script:
    - mix test